import {
  AudioLines,
  Blend,
  Captions,
  CircleDashed,
  Clapperboard,
  ClipboardPaste,
  Copy,
  Crop,
  Download,
  Eraser,
  Expand,
  FilePlus,
  Film,
  FlaskConical,
  FolderOpen,
  Grid3x3,
  Group,
  Import,
  Info,
  Keyboard,
  ListChecks,
  ListX,
  type LucideIcon,
  Magnet,
  MapPin,
  Maximize,
  Minimize,
  Music,
  Pause,
  Play,
  Redo2,
  Repeat,
  Save,
  SaveAll,
  Scan,
  Scissors,
  Settings,
  Sparkles,
  Square,
  SquareDashedMousePointer,
  SquareSplitHorizontal,
  TextCursorInput,
  Type,
  Undo2,
  Ungroup,
  X,
  ZoomIn,
  ZoomOut,
  BookmarkPlus,
  ScissorsLineDashed,
  ChartNoAxesColumnDecreasing,
  ScanFace,
  UserRound,
  Highlighter,
  Smile,
  Layers,
  Rows2,
  PictureInPicture2,
  Bot
} from 'lucide-react'
import type { CommandId } from './commands'

/** Icon shown next to a command in the menus and the right-click menu. */
export const COMMAND_ICONS: Partial<Record<CommandId, LucideIcon>> = {
  newProject: FilePlus,
  openProject: FolderOpen,
  saveProject: Save,
  saveProjectAs: SaveAll,
  importMedia: Import,
  properties: Settings,
  render: Clapperboard,
  undo: Undo2,
  redo: Redo2,
  split: SquareSplitHorizontal,
  deleteSelection: X,
  rippleDelete: ListX,
  trimToSelection: Crop,
  selectInTimeSelection: SquareDashedMousePointer,
  zoomToSelection: ZoomIn,
  clearTimeSelection: Eraser,
  playSelection: Play,
  copy: Copy,
  cut: Scissors,
  paste: ClipboardPaste,
  removeFades: Blend,
  selectAll: ListChecks,
  group: Group,
  ungroup: Ungroup,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  zoomFit: Expand,
  addVideoTrack: Film,
  addAudioTrack: Music,
  addMarker: MapPin,
  panCrop: Crop,
  insertText: Type,
  captions: Captions,
  editText: TextCursorInput,
  mask: CircleDashed,
  fillFrame: Maximize,
  fitFrame: Minimize,
  toggleSafeAreas: Scan,
  toggleSnapping: Magnet,
  toggleCrossfades: Blend,
  toggleQuantize: Grid3x3,
  toggleLoop: Repeat,
  play: Play,
  pause: Pause,
  stop: Square,
  playStop: Play,
  playPause: Play,
  shortcuts: Keyboard,
  about: Info,
  loadDemoMedia: FlaskConical,
  videoFx: Sparkles,
  audioFx: AudioLines,
  youtube: Download,
  toggleLinkDownloads: Download,
  saveSoundEffect: BookmarkPlus,
  removeSilences: ScissorsLineDashed,
  autoDucking: ChartNoAxesColumnDecreasing,
  autoReframe: ScanFace,
  autoZoom: ZoomIn,
  blurredBackground: Layers,
  splitScreen: Rows2,
  pictureInPicture: PictureInPicture2,
  aiAgents: Bot,
  highlightKeywords: Highlighter,
  addEmoji: Smile,
  removeBackground: UserRound
}

/** Commands drawn in red (destructive). */
export const DANGER_COMMANDS = new Set<CommandId>(['deleteSelection', 'rippleDelete'])
